---
title: 'Barriers and facilitators of clinical trial participation in neurodegenerative diseases: A systematic review and meta-analysis'
author:
  - name: Daphne N. Weemering
    affiliation: Neuro
  - name: Anita Beelen
    affiliation: Rehab, Excel
  - name: Tessa Kliest
    affiliation: Neuro
  - name: Lucie A.G. van Leeuwen
    affiliation: Neuro
  - name: Leonard H. van den Berg
    affiliation: Neuro
  - name: Ruben P.A. van Eijk
    email: 'r.p.a.vaneijk-2@umcutrecht.nl'
    affiliation: Neuro, Julius
    correspondingauthor: true
address:
  - code: Neuro
    address: Department of Neurology, UMC Utrecht Brain Centre, University Medical Centre Utrecht, Utrecht, the Netherlands.
  - code: Rehab
    address: Department of Rehabilitation, Physical Therapy Science & Sports, UMC Utrecht Brain Centre, University Medical Centre Utrecht, the Netherlands
  - code: Excel
    address: Centre of Excellence for Rehabilitation Medicine, UMC Utrecht Brain Centre, University Medical Centre Utrecht, and De Hoogstraat Rehabilitation, Utrecht, the Netherlands
  - code: Julius
    address: Biostatistics & Research Support, Julius Centre for Health Sciences and Primary Care, University Medical Centre Utrecht, Utrecht, the Netherlands
abstract: |
  **Background**: Study participants in clinical trials for neurodegenerative disorders are selective and underrepresentative for all patients with the disease. This limits generalizability of study results and makes the safety and efficacy of interventions unknown for the majority of patients. In this study, we aim to identify barriers and facilitators for clinical trial participation. These identified factors inform recommendations for the inclusion of the broader population. 

  **Methods**: We conducted a systematic literature search of quantitative and qualitative articles reporting barriers and facilitators of clinical trials for neurodegenerative diseases. Studies evaluating participating in non-interventional research were excluded. Barriers and facilitators were extracted; the frequency with which patients identified barriers/facilitators were pooled across studies and summarized as proportions. 
  
  **Results**: Thirty-six unique studies were included, enrolling a total of 5113 patients and/or people related to Alzheimer's disease (n=1261), Parkinson's disease (n=2789), Huntington's disease (n=696) or amyotrophic lateral sclerosis (n=367). The most commonly mentioned barriers/facilitators were XXX.  
keywords: 
  - Trial participation
  - neurodegenerative diseases
journal: "Elsevier journal"
date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography: mybibfile.bib
linenumbers: false
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
---

# Introduction
```{r, echo = F}
library(lorem)
lorem::ipsum(paragraphs = 5)

```

# Methods 
## Search strategy
The aim of the systematic review was to identify all original research articles, both qualitative and quantitative, that report on barriers and facilitators to participation in clinical trials. Studies were identified in the PubMed and EMBASE databases, as well as by screening reference lists from relevant reviews. The search was limited to the most common neurogenerative diseases: Alzheimer’s disease (AD), Parkinson’s disease (PD), Huntington’s disease (HD) and amyotrophic lateral sclerosis (ALS) [@hou2019; @zahra2020]. Search terms included “barriers”, “facilitators”, “clinical trials”, “participation”, “Alzheimer’s disease”, “Parkinson’s disease”, “Huntington’s disease”, and “amyotrophic lateral sclerosis”, and their synonyms (**Supplement 1**). The search was discussed with an information specialist and was limited to qualitative and quantitative studies written in English and Dutch. The final reference list was generated in January 2022. 

## Study selection
After removal of duplicates, the reference list was analyzed using Automated Systematic Review (ASReview, version v0.17rc0) – a machine learning framework which labels and subsequently ranks titles and abstracts based on the relevance of the key terms entered into the software [@vandeschoot2021]. Relevant key terms were: “facilitator”, “barrier”, “participate”, “refusal”, “perspective”, “patient selection”, “retention”, “attitude”, “recruit”, “enroll”, “accrual”, “attrition”, and “clinical trial”. “Animal” and/or “mouse” were marked as irrelevant key terms. 

The first 200 ranked abstracts were screened by two reviewers (TK and LAGvL) and were discussed until consensus was reached (**Supplement 2.1**). The following abstract were screened by one reviewer (TK). References were eligible for full-text screening if the abstract reported facilitators and barriers to participation in clinical trials. Full text articles had to meet the following criteria to be using in the thematic and/or meta-analysis (**Supplement 2.2**): original research published in a peer reviewed journal, reporting barriers and/or facilitators for (a) clinical trial(s) with a drug therapy, concerning patients with AD, PD, HD, or ALS. Qualitative studies were assessed by using the Critical Appraisal Skills Program (CASP- quality assessment tool [@casp2018]. 

## Data extraction
Data on facilitators and barriers were independently extracted from the articles by TK and LAGvL with a pre-prepared extraction scheme. The first ten articles and the corresponding study extraction schemes were discussed in depth and compared between TK and LAGvL. Once consensus was reached, data of interest were extracted independently. Studies solely reporting demographics, participants at risk of neurodegenerative diseases, outcomes represented by $\leq 5\%$ of the sample size, or articles where the patient population with neurodegenerative disease was $\leq 50\%$ of the total sample size (e.g., studies including various disease populations) were excluded from the analysis.

All barriers and facilitators for trial participation were reported from patients, caregivers and/or health care professionals (HCPs). The identified barriers and facilitators were clustered in three overarching themes: patient related-, study procedures related- and HCP related factors regarding (not) participating. The study procedures related- and HCP related factors were considered modifiable – factors that can be applied to and amended before and during clinical trial. The patient related factors were appraised as motivators and beliefs – intrinsic factors that cannot be amended during the design phase of a trial to improve enrollment. After all barriers and facilitators were collected and grouped, TK did a final review to identify whether the created themes and subthemes represented the reported barriers and facilitators identified in the analyzed articles. Final consensus on the (sub)themes was reached during an in-depth meeting with RPAvE, AB, DW and TK.

## Statistical analysis
The quantitative data (i.e., the proportion of patients reporting on barriers/facilitators in closed interview questions/surveys) were synthesized using meta-analyses to obtain overall effect size estimates for each of the modifiable barriers and facilitators. The meta-analyses were performed exclusively on patient-reported barriers and facilitators. 

The proportions for each barrier/facilitator were logit transformed prior to pooling. Random intercept logistic regression models were fitted, accounting for the binomial structure of the data and to account for the between-study heterogeneity [@stijnen2010]. Proportions and $95\%$ Clopper-Pearson (i.e., exact binomial confidence interval) confidence intervals [@clopper1934] are reported for each barrier/facilitator. To give a good indication of the variance between the studies, the following heterogeneity statistics were provided: the between study variance parameter $\tau^2$, the Q-statistic, and the I2- and H2-statistics, the latter two with a $95\%$ confidence interval. 

Heterogeneity between studies could be expected due to the different disease populations and the different types of responders (i.e., patients, caregivers, HCPs or a combination of these). Therefore, subgroup analyses were performed on each barrier/facilitator, with the disease populations and the responder type as subgroups. We fitted mixed-effects model, assuming the subgroups to be fixed and the studies within the subgroups to be random. Cochran’s Q [@cochran1954] was used to determine whether overall differences in effect size were significant. We used the $I^2$ statistic [@higgins2002] to determine between study heterogeneity. P-values are reported with decimals – values smaller or around 0.05 are considered statistically significant. All quantitative analyses are performed in R (version 4.2.1 (2022-06-23)) [@Rmanual] with the ‘meta’ package [@meta]. 

# Results
In total, 560 abstracts were reviewed (AD: n = 206, PD: n = 177, HD: n = 69, ALS: n = 108), resulting in the inclusion of 85 abstracts (AD: n = 61, PD: n = 15, HD: n = 4, ALS: n = 5) for full text scrutinization. A Cohen’s kappa of 0.86 was established between the reviewers, indicating an almost perfect agreement for abstract review of 200 articles. Of the 85 full text articles, 49 articles were excluded based on the following reasons: the article did not include participants with a diagnosis (e.g., people at risk or health elderly (n = 23)), did not assess barriers or facilitators for participation in drug therapy clinical trials (n = 23), and were not an original research article (n = 3; see **figure 1** for the study selection flow diagram). Thus, we included 36 full text articles (AD: n = 17, PD: n = 12, HD: n = 4, ALS: n = 2, PD $+$ ALS: n = 1) for the final data extraction. No qualitative studies were excluded based on the results of the CASP (**Supplement 3**).

## Study characteristics
**Table 1** shows the main characteristics of the included studies. Two articles [@cox2019; @damron2021] included both qualitative and quantitative study methods; one article [@solomon2012] included two different qualitative methods and one article [@dasmahapatra2017] included both people with PD and ALS. All methods and patient populations were separately analyzed and reported. Finally, the review resulted in the inclusion of 25 quantitative studies (survey/structured interview: n = 4582) and 15 qualitative studies (open-ended questions/focus groups/semi-structured interviews: n = 531). Of the included studies, 19 (48%) focuses on AD, 14 (35%) on PD, 4 (10%) on HD, and 3 (8%) on ALS. Per disease, data was collected of 1261 people with AD, 2789 people with PD, 696 people with HD, and 367 people with ALS. Thus, a total of 5113 people with/related to neurodegenerative diseases were included. 

Of the included studies, 65% was conducted in the United States (US). The remainder of the studies was conducted in Sweden (8%), Australia (5%), Finland (5%), and the United Kingdom (UK), Israel, Europe (several countries), Singapore, US together with UK, and Canada (the latter countries all occurred once). The focus of the studies also varied in terms of perspective and data collection method. 19 studies (48%) focused solely on the perspective of the patient. 8 studies (20%) included the perspective of both patients and caregivers, the perspective of the caregivers was incorporated in 7 studies (18%), 4 studies (10%) included patients, caregivers, and healthcare professionals, and 2 studies (5%) investigated healthcare professionals’ perspectives on factors influencing trial participation. Regarding the data collection method, 24 studies (60%) used a survey, 11 studies (28%) collected data using semi-structured interviews, 2 studies (5%) used open-ended question, 2 other studies conducted focus groups, and 1 study (3%) used a structured interview to collect data. 

## Thematic analysis of qualitative data
Several themes and subthemes corresponding to barriers, facilitators, motivators, and beliefs for trial participation were identified in the studies. These (sub)themes are displayed in **figure 2**. 

## Meta-analyses of quantitative data
The meta-analyses of the proportional data are displayed in **figure 3**. The primary barrier/facilitator for engaging in clinical trials under patients with a neurodegenerative disease, was awareness ($N_{studies}$ = 1, estimate (95% CI) = 78.5% (75.6 to 81.2)). Second and third ranked barriers/motivators for trial participation were the relationship with clinical staff ($N_{studies}$ = 6, estimate (95% CI) = 75.0% (58.8 to 86.3)) and placebo/sham use ($N_{studies}$ = 5, estimate (95% CI) = 71.2 (21.3 to 95.8)). 

Due to synthesizing data of different diseases and different types of responders, between-study heterogeneity was expected a priori, and was found for each barrier/facilitator. The heterogeneity statistics are reported in **table 2**. The Q-statistics were significantly different from zero ($p < 0.001$), the $I^2$ statistics also mark substantial heterogeneity (>90%). 


# Discussion




# References {-}










